# Generated by Django 3.2.8 on 2021-11-24 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='method',
            field=models.CharField(choices=[('KO', 'Knockout'), ('JD', "Judge's Decision"), ('TO', 'Tap Out'), ('OA', 'Out of the Arena'), ('PT', 'Pit'), ('DR', 'Draw'), ('WU', 'Winner Unknown'), ('NW', 'No Winner Declared')], default='KO', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
