# Generated by Django 3.2.8 on 2021-11-28 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211124_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.AddField(
            model_name='registration',
            name='signup_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, upload_to='event_logos/%Y/'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='contest',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.contest'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='media_external',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='fight',
            name='media_internal',
            field=models.FileField(blank=True, upload_to='fight_media/%Y/'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='method',
            field=models.CharField(choices=[('KO', 'Knockout'), ('JD', "Judge's Decision"), ('TO', 'Tap Out'), ('OA', 'Out of the Arena'), ('PT', 'Pit'), ('DR', 'Draw'), ('WU', 'Winner Unknown'), ('NW', 'No Winner Declared'), ('NM', 'No Method Declared')], default='NM', max_length=2),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='logo',
            field=models.ImageField(blank=True, upload_to='franchise_logos/%Y/'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='robot',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='robot',
            name='opt_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='robot',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to='team_logos/%Y/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='image',
            field=models.ImageField(blank=True, upload_to='robot_images/%Y/'),
        ),
    ]
