# Generated by Django 3.2.8 on 2021-11-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211128_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='signup_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
