# Generated by Django 3.2.8 on 2021-11-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_registration_signup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
